### PR TITLE
Update K8s and CAPI dependencies

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

Update Kubernetes and Cluster API related dependencies for the provider.

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
@elmiko let me know if this is alright, or if there's a reason to keep the versions here older.

**Comment by elmiko** [comment]
thanks again @killianmuldoon , like #55, i would like to give this a manual test just to make sure, i will plan this for monday.

**Comment by elmiko** [comment]
still testing this, i'm having some issues getting kube 1.25.3 to work with kind. i do have a couple requests though:

1. update the Dockerfile to use go lang 1.19
2. update the README section on supported version to indicate the newer go lang and capi versions

**Comment by elmiko** [comment]
just out of curiosity, i'm having some issues getting the docker control plane machine to come up with kube 1.25.3, will this require the proxy update from #55  ?

**Comment by elmiko** [comment]
when i tested against kube 1.23.5 everything seemed to work, but kube 1.24.7 didn't. not quite sure what's up with that.

**Comment by elmiko** [comment]
all my tests were with capi 1.2.4, fwiw

**Comment by killianmuldoon** [comment]
I think this is probably related to changes in https://github.com/kubernetes-sigs/kind/releases/tag/v0.13.0 - so to make this work I think it will have to update the cgroup driver. I didn't actually test it with v1.24+ until I saw this comment. 

Let me see if I can get a fix.

**Comment by elmiko** [comment]
it turns out my problem was exactly related to the cgroup issue, i changed my machine template specs and was able to deploy on 1.24+. i have not tested this PR though. i'll give another look today/tomorrow. i don't think it will be an issue though.

**Comment by elmiko** [comment]
also, with those changes to the template (removing the cgroup driver) we should update the README to say this is compatible with kube 1.24+

**Comment by killianmuldoon** [comment]
Yeah - we could have a second template that works with 1.24 and below. CAPD works using ClusterClass and a version-aware patch, which could be a good improvement here too 🙂

**Comment by elmiko** [comment]
yeah, having a ClusterClass deployment for kubemark clusters would be a nice update

**Review by elmiko — CHANGES_REQUESTED** [review]
hey @killianmuldoon , no rush, i'm happy to merge this once the readme is updated with the kube, go, and cluster-api versions.

**Comment by killianmuldoon** [comment]
@elmiko The latest push has the version + Readme changes that should signal properly to users what K8s version this is compatible with.

**Review by elmiko — COMMENTED** [review]
thanks for the updates @killianmuldoon !

/lgtm
/approve

**Review by elmiko — APPROVED** [review]

**Pull request merged**
