### PR TITLE
update for capi 1.4 and k8s 1.26

### PR DESCRIPTION
**Pull request by elmiko**
**What this PR does / why we need it**:

updating to capi release 1.4.3 and the related kubernetes versions.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
fixes #

**Special notes for your reviewer**:

**Release notes**:

```release-note
```

### CODE REVIEW

**Comment by elmiko** [comment]
i've been testing this locally and i think it's ready for merge

```
Every 2.0s: kubectl --kubeconfig /tmp/km.kubeconfig get pods -A                           mike: Fri Jul 14 21:27:31 2023

NAMESPACE     NAME                                                READY   STATUS     RESTARTS   AGE
kube-system   calico-kube-controllers-5f94594857-zqtz5            1/1     Running    0          4m8s
kube-system   calico-node-9vdpr                                   1/1     Running    0          4m8s
kube-system   calico-node-bxqks                                   0/1     Init:0/3   0          4m8s
kube-system   calico-node-cpcbs                                   0/1     Init:0/3   0          4m8s
kube-system   calico-node-rhh8m                                   0/1     Init:0/3   0          4m8s
kube-system   calico-node-vv922                                   0/1     Init:0/3   0          4m8s
kube-system   coredns-787d4945fb-sqrd5                            1/1     Running    0          4m59s
kube-system   coredns-787d4945fb-zvdzq                            1/1     Running    0          4m59s
kube-system   etcd-km-cp-control-plane-54zfm                      1/1     Running    0          5m3s
kube-system   kube-apiserver-km-cp-control-plane-54zfm            1/1     Running    0          5m2s 
kube-system   kube-controller-manager-km-cp-control-plane-54zfm   1/1     Running    0          5m3s
kube-system   kube-proxy-56pkf                                    1/1     Running    0          4m37s
kube-system   kube-proxy-cn2bk                                    1/1     Running    0          4m38s
kube-system   kube-proxy-dgnbh                                    1/1     Running    0          4m37s
kube-system   kube-proxy-ndqcr                                    1/1     Running    0          4m59s
kube-system   kube-proxy-s59g5                                    1/1     Running    0          4m36s
kube-system   kube-scheduler-km-cp-control-plane-54zfm            1/1     Running    0          5m3s
```

**Review by vincepri — APPROVED** [review]
/lgtm
/hold 

feel free to unhold when ready

**Comment by elmiko** [comment]
thanks @vincepri ! i'm just cleaning up some docs and whatnot then i'll merge

**Pull request merged**
