### PR TITLE
Update test deployment manifest for workload cluster

### PR DESCRIPTION
**Pull request by apoorva-jn**
**What this PR does / why we need it**:
Update test deployment manifest for workload cluster

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
Updating test deployment manifest for workload cluster. So that Kubemark nodes can talk to the docker socket on the host instance.

**Special notes for your reviewer**:

**Release notes**:

```
NONE
```

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by agradouski** [comment]
looks like go-linter PR check is failing, but for unrelated to this PR reason, should be fixed in a separate PR.
/approve

**Comment by agradouski** [comment]
looks like go-linter PR check is failing, but for unrelated to this PR reason, should be fixed in a separate PR.
/approve

**Comment by elmiko** [comment]
i'm going to manually merge this, then we can fix the linter issue

**Comment by elmiko** [comment]
created https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/pull/42 to address the linting issues

**Pull request merged**
