### PR TITLE
update module spec to match github org and update dependencies

### LINKED ISSUE #4: kubernetes and cluster api dependencies need updating
as of this writing, capk is based on kubernetes 1.19 and capi 0.3.11. wheres the current versions are 1.21 and 0.3.16, respectively. deps should be updated.

### PR DESCRIPTION
**Pull request by elmiko**
This changes the organization from the old location to the
kubernetes-sigs org. It also incorporates the changes from running `make
modules`.

Update RESTConfig call to include a user agent string for the REST
client.

fixes #4

### CODE REVIEW

**Comment by elmiko** [comment]
still testing this out locally

**Comment by elmiko** [comment]
updated to include 0.4.2 cluster-api, still need to run a few manual tests

**Comment by elmiko** [comment]
found a few regressions while testing against CAPI 0.4.2 release. adding a few fixups

**Review by cchengleo — APPROVED** [review]

**Review by elmiko — COMMENTED** [review]
i'm confident that the changes here bring the actuator up to the standards for 0.4.2 release of capi. going to try self-approving
/lgtm

**Comment by elmiko** [comment]
@agradouski or @cchengleo could you try adding an `/lgtm` here?

**Review by cchengleo — APPROVED** [review]
/lgtm

**Comment by elmiko** [comment]
hmm, think i might need to update the owners

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
