### PR TITLE
update configs for release 0.5.0

### LINKED ISSUE #61: Propose release version 0.5.0
hello cluster-api provider kubemark community,

i would like to propose that we create a new release, version 0.5.0 to capture these recent changes:

* updated dependencies for Cluster API version 1.3
* updated dependencies for Kubernetes version 1.25
* simplified kustomize configuration
* updated kube-proxy version in default manifests
* kubemark provider now sets ProviderID on KubemarkMachine during reconcile
* updates to build tooling

### PR DESCRIPTION
**Pull request by elmiko**
**What this PR does / why we need it**:

This PR updates the metadata configuration for a new 0.5.0 release. after merging we will add a tag on this commit to denote the release.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #61

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
One Q - should the README at the same time?

**Comment by elmiko** [comment]
good point, i'll review the readme

**Comment by elmiko** [comment]
updated the version in the README for the example command

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Pull request merged**
