### PR TITLE
Update rbac-proxy

### LINKED ISSUE #36: update and standardize kube-rbac-proxy version
currently the kubemark provider deployment manifests use version `v0.4.1`, and `v0.5.0`, but the upstream is at `v0.11.0` (see https://github.com/brancz/kube-rbac-proxy/releases). there are 2 primary places where the manifests specify kube-rbac-proxy use:

* https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/blob/main/config/manager/manager_auth_proxy_patch.yaml#L13
* https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/blob/main/config/default/manager_auth_proxy_patch.yaml#L13

since these are part of the kustomize templating for the kubemark manifests, it would be nice to see the value for the kube-rbac-proxy converted to a variable so that we can make it standard across the components.

additionally, when updating the components, we might need to change the command line flags as mentioned in [this comment](https://github.com/kubernetes-sigs/cluster-api-provider-kubemark/issues/31#issuecomment-1046045634).

to fix this issue:
1. convert the kube-rbac-proxy usages to kustomize (similar to how the controller deployment is handled)
2. update version to `v0.11.0`
3. update command line flags to proxy
4. test

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

Update kube-rbac-proxy and simplify the kustomize flow, removing a duplicate patch for metrics endpoint authentication.

Fixes #36 

```release-note
Update kube-rbac-proxy from 0.5.0 -> 0.13.0
```

### CODE REVIEW

**Comment by killianmuldoon** [comment]
/hold

Still need to test this and ensure there's no breaking changes.

**Review by killianmuldoon — COMMENTED** [review]
/hold

Still need to test this and ensure there's no breaking changes.

**Comment by elmiko** [comment]
thanks for the PR @killianmuldoon , it looks good to me, and the tests seem to agree. happy to merge this once you've had a chance to test it.

**Comment by killianmuldoon** [comment]
/remove-hold

Did a couple of extra cleanups to kustomize, but the only diff between this and main after generation should be the rbac-proxy version.

**Comment by elmiko** [comment]
@killianmuldoon i checked out your branch and tried to run `make docker-build` but it produced an error. did i miss a step?

```
mike@capivm:~/cluster-api-provider-kubemark$ make docker-build
DOCKER_BUILDKIT=1 docker build --pull --build-arg goproxy=https://proxy.golang.org,direct --build-arg ARCH=amd64 . -t localhost:5000/cluster-api-kubemark-controller-amd64:dev --file Dockerfile
[+] Building 21.3s (19/19) FINISHED                                                                                                                                           
 => [internal] load build definition from Dockerfile                                                                                                                     0.0s
 => => transferring dockerfile: 1.74kB                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                          0.0s
 => resolve image config for docker.io/docker/dockerfile:experimental                                                                                                    0.6s
 => CACHED docker-image://docker.io/docker/dockerfile:experimental@sha256:600e5c62eedff338b3f7a0850beb7c05866e0ef27b2d2e8c02aa468e78496ff5                               0.0s
 => [internal] load metadata for gcr.io/distroless/static:nonroot                                                                                                        0.4s
 => [internal] load metadata for docker.io/library/golang:1.15                                                                                                           0.3s
 => [builder 1/9] FROM docker.io/library/golang:1.15@sha256:ea080cc817b02a946461d42c02891bf750e3916c52f7ea8187bccde8f312b59f                                             0.0s
 => [internal] load build context                                                                                                                                        0.0s
 => => transferring context: 160.41kB                                                                                                                                    0.0s
 => CACHED [stage-1 1/3] FROM gcr.io/distroless/static:nonroot@sha256:ed05c7a5d67d6beebeba19c6b9082a5513d5f9c3e22a883b9dc73ec39ba41c04                                   0.0s
 => => resolve gcr.io/distroless/static:nonroot@sha256:ed05c7a5d67d6beebeba19c6b9082a5513d5f9c3e22a883b9dc73ec39ba41c04                                                  0.0s
 => CACHED [builder 2/9] WORKDIR /workspace                                                                                                                              0.0s
 => CACHED [builder 3/9] COPY go.mod go.mod                                                                                                                              0.0s
 => CACHED [builder 4/9] COPY go.sum go.sum                                                                                                                              0.0s
 => CACHED [builder 5/9] RUN go mod download                                                                                                                             0.0s
 => [builder 6/9] COPY main.go main.go                                                                                                                                   0.0s
 => [builder 7/9] COPY api/ api/                                                                                                                                         0.0s
 => [builder 8/9] COPY controllers/ controllers/                                                                                                                         0.0s
 => [builder 9/9] RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager main.go                                                               19.4s
 => [stage-1 2/3] COPY --from=builder /workspace/manager .                                                                                                               0.1s
 => exporting to image                                                                                                                                                   0.2s
 => => exporting layers                                                                                                                                                  0.2s
 => => writing image sha256:970184d3a975b8807ff5133515913691ec47f23d8d28b57078058cbdd1483816                                                                             0.0s
 => => naming to localhost:5000/cluster-api-kubemark-controller-amd64:dev                                                                                                0.0s
MANIFEST_IMG=localhost:5000/cluster-api-kubemark-controller-amd64 MANIFEST_TAG=dev make set-manifest-image
make[1]: Entering directory '/home/mike/cluster-api-provider-kubemark'
Updating kustomize image patch file for manager resource
sed -i'' -e 's@image: .*@image: '"localhost:5000/cluster-api-kubemark-controller-amd64:dev"'@' ./config/manager/manager_image_patch.yaml
sed: can't read ./config/manager/manager_image_patch.yaml: No such file or directory
make[1]: *** [Makefile:182: set-manifest-image] Error 2
make[1]: Leaving directory '/home/mike/cluster-api-provider-kubemark'
make: *** [Makefile:146: docker-build] Error 2
```

**Comment by elmiko** [comment]
looks like the Makefile just needs an update

```
mike@capivm:~/cluster-api-provider-kubemark$ git diff Makefile
diff --git a/Makefile b/Makefile
index 07f78df..90490e1 100644
--- a/Makefile
+++ b/Makefile
@@ -179,12 +179,12 @@ docker-push-manifest: ## Push the fat manifest docker image.
 .PHONY: set-manifest-image
 set-manifest-image:
        $(info Updating kustomize image patch file for manager resource)
-       sed -i'' -e 's@image: .*@image: '"${MANIFEST_IMG}:$(MANIFEST_TAG)"'@' ./config/manager/manager_image_patch.yaml
+       sed -i'' -e 's@image: .*@image: '"${MANIFEST_IMG}:$(MANIFEST_TAG)"'@' ./config/default/manager_image_patch.yaml
 
 .PHONY: set-manifest-pull-policy
 set-manifest-pull-policy:
        $(info Updating kustomize pull policy file for manager resource)
-       sed -i'' -e 's@imagePullPolicy: .*@imagePullPolicy: '"$(PULL_POLICY)"'@' ./config/manager/manager_pull_policy.yaml
+       sed -i'' -e 's@imagePullPolicy: .*@imagePullPolicy: '"$(PULL_POLICY)"'@' ./config/default/manager_pull_policy.yaml
 
 ## --------------------------------------
 ## Release
```

**Comment by elmiko** [comment]
fwiw, with the makefile changes in place this PR worked as expected for me.

i used CAPI v 1.2.4 and kubernetes v1.23.5

**Comment by killianmuldoon** [comment]
Thanks for catching that! I've updated the Makefile now so this should be working.

**Review by elmiko — COMMENTED** [review]
thanks @killianmuldoon !
/approve
/lgtm

**Pull request merged**
