### PR TITLE
update for cluster-api 1.6 and kubernetes 1.28

### PR DESCRIPTION
**Pull request by elmiko**
**What this PR does / why we need it**:

this change updates the dependencies for cluster-api, kubernetes and controller runtime.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
fixes #

**Special notes for your reviewer**:

**Release notes**:

```release-note
Add support for Cluster API 1.6 and Kubernetes 1.28
```

### CODE REVIEW

**Comment by elmiko** [comment]
still doing some local testing on this

/hold

**Comment by elmiko** [comment]
preliminary testing with `make test-e2e`, need to fixup the templates to use kubernetes 1.28.

```
$ kubectl --kubeconfig /tmp/km.kubeconfig get nodes
NAME                        STATUS   ROLES           AGE     VERSION
km-cp-control-plane-dflb5   Ready    control-plane   4m31s   v1.27.3
km-wl-kubemark-md-0-dv4hz   Ready    <none>          4m19s   v1.27.3
km-wl-kubemark-md-0-nb7kx   Ready    <none>          4m20s   v1.27.3
km-wl-kubemark-md-0-rv8n9   Ready    <none>          4m19s   v1.27.3
km-wl-kubemark-md-0-xsc5h   Ready    <none>          4m19s   v1.27.3
```

**Comment by elmiko** [comment]
i've done more testing with 1.28 kubernetes, this is ready imo

/hold cancel

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

Haven't tested - but the changes look good to me.

As a heads up - for the CAPI 1.7 bump the api versions and cluster api imports will need to be bumped so it'll end up being a substantial change.

**Comment by elmiko** [comment]
thanks for the heads up @killianmuldoon !

**Pull request merged**
